$ANSIBLE_VAULT;1.1;AES256
35653563383036313063346562653732633864633733666231646664303562306433306666353562
6264316266316363343063643434366335323031313966350a356435393732616137363866656239
32643162646636376333343733353763366334373038323039326434623934616562616338346465
3938353661333365330a633830363835383064373132653632303561616666313664376331643264
61363164386435643765633330336132323830353337616535356166393466616139643330303366
62333632306630313866383231356664633032363432396137666230383034356535396539396330
39323366356537653966643834326431386430316163366631353165633331623330396438386365
66633164643830333235346661326533393963666239656136666534343139313430393638633535
37353130353931636236333566613237646266626339386132643133633839326130636137306639
64306362656263663434346363396634353938353235356537313562633865326436353435366630
39303861316133613634323439333034643936623566326437373534393139376139626266623561
30653535643264666131633833616439333031626630383964343931656436623730306163356264
63633633313234333263633736633236313633323139323032636365363133396430616361376434
31646136343664366266313636306635326434383364303833643531613038316439633932393961
61643532376634666436373830623661323263623866393164353162386433346234636136363634
30393934376336353863363030656631303030666531333061333134303933383037623066306462
63646531326630666538633734353238313531363766343133303230396636336530616666366635
38303535623739653061333439323864323438396330613335376232363233303639396634323266
35386430393936636331626130386238383936343734363462326337623062356338393334333230
66653439663935393465346661393765303137333062656262613034363130313238343333303434
39653236366231626532663638613032313462646431353135643336366162656664643933353461
39636232366437656466646138346636323435306437316233646564393539383932383935636330
64636166643037323739323463313737313235346634616233363162326535386564316134353037
35613038396163613233343564376663653765333538386635386437313134383064336261646562
3666
